export * from './base.qr';
export * from './image-fill.qr';
export * from './image.qr';
export * from './func.qr';
export * from './dsj.qr';
export * from './solid.qr';
export * from './circle.qr';
export * from './rand-rect.qr';
export * from './line.qr';
